# Multi-agent project bootstrap (PowerShell)
# Generated by multi-agent-template; do not edit by hand.

param(
    [string]$ProjectRoot = $PSScriptRoot,
    [string]$Agents = "{{ cookiecutter.agents }}"
)

$ErrorActionPreference = "Stop"

Write-Host "[bootstrap] Project root: $ProjectRoot"
Write-Host "[bootstrap] Agents: $Agents"

# TODO (P-0059 Phase 1.4): implement N-clone init
#   1. cd $ProjectRoot && git init
#   2. Initial commit of skeleton
#   3. For each agent in $Agents (split by comma):
#      - git clone $ProjectRoot ../agent-<name>
#      - cd ../agent-<name> && git checkout -b feature/<name>
#      - Configure .gitattributes merge=ours driver
#   4. mkdir shared_state/<project_name>/{proposals,knowledge}
#   5. pip install governance-core (in each clone's venv)
#   6. governance-core install (each clone)

Write-Host "[bootstrap] Not yet implemented (Phase 1.4)."
exit 2
