#!/usr/bin/env bash
# Multi-agent project bootstrap (POSIX shell)
# Generated by multi-agent-template; do not edit by hand.

set -euo pipefail

PROJECT_ROOT="${1:-$(dirname "$0")}"
AGENTS="${2:-{{ cookiecutter.agents }}}"

echo "[bootstrap] Project root: $PROJECT_ROOT"
echo "[bootstrap] Agents: $AGENTS"

# TODO (P-0059 Phase 1.4): implement N-clone init (mirror bootstrap.ps1)

echo "[bootstrap] Not yet implemented (Phase 1.4)."
exit 2
